# Generated by Django 5.2.7 on 2025-11-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='birth_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(db_index=True, max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publication_date',
            field=models.DateField(db_index=True, verbose_name='Fecha de Publicación'),
        ),
    ]
